spring:
  main:
    banner-mode: off
    web-application-type: none
logging:
  level:
    root: OFF

simulation:
  server:
    port: 100
  file:
    name: "file.txt"

---

spring:
  config:
    activate:
      on-profile: web
  main:
    banner-mode: console
    web-application-type: servlet
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
    root: info